// Code generated by protoc-gen-go. DO NOT EDIT.
// source: utlcore/email.proto

package utlcore // import "grpc-swagger/protos/utlcore"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailRequest_Type int32

const (
	EmailRequest_UNDEFINED               EmailRequest_Type = 0
	EmailRequest_ACTIVATION              EmailRequest_Type = 1
	EmailRequest_WELCOME                 EmailRequest_Type = 2
	EmailRequest_BIND_PHONE_NUMBER       EmailRequest_Type = 3
	EmailRequest_CHANGE_PHONE_NUMBER     EmailRequest_Type = 4
	EmailRequest_RESET_PASSWORD          EmailRequest_Type = 5
	EmailRequest_RESET_CURRENCY_PASSWORD EmailRequest_Type = 6
	EmailRequest_WITHDRAW_DEPOSIT        EmailRequest_Type = 7
	EmailRequest_CREATE_API_KEY          EmailRequest_Type = 8
)

var EmailRequest_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "ACTIVATION",
	2: "WELCOME",
	3: "BIND_PHONE_NUMBER",
	4: "CHANGE_PHONE_NUMBER",
	5: "RESET_PASSWORD",
	6: "RESET_CURRENCY_PASSWORD",
	7: "WITHDRAW_DEPOSIT",
	8: "CREATE_API_KEY",
}
var EmailRequest_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"ACTIVATION":              1,
	"WELCOME":                 2,
	"BIND_PHONE_NUMBER":       3,
	"CHANGE_PHONE_NUMBER":     4,
	"RESET_PASSWORD":          5,
	"RESET_CURRENCY_PASSWORD": 6,
	"WITHDRAW_DEPOSIT":        7,
	"CREATE_API_KEY":          8,
}

func (x EmailRequest_Type) String() string {
	return proto.EnumName(EmailRequest_Type_name, int32(x))
}
func (EmailRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_email_60d6484c15673ba5, []int{0, 0}
}

type EmailRequest struct {
	Type                 EmailRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.EmailRequest_Type" json:"type,omitempty"`
	Email                string            `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Language             LanguageType      `protobuf:"varint,3,opt,name=language,proto3,enum=protos.LanguageType" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_60d6484c15673ba5, []int{0}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetType() EmailRequest_Type {
	if m != nil {
		return m.Type
	}
	return EmailRequest_UNDEFINED
}

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailRequest) GetLanguage() LanguageType {
	if m != nil {
		return m.Language
	}
	return LanguageType_UNDEFINED
}

type EmailResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	DayLimit             int64      `protobuf:"varint,2,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	HourLimit            int64      `protobuf:"varint,3,opt,name=hour_limit,json=hourLimit,proto3" json:"hour_limit,omitempty"`
	MinuteLimit          int64      `protobuf:"varint,4,opt,name=minute_limit,json=minuteLimit,proto3" json:"minute_limit,omitempty"`
	Expire               int64      `protobuf:"varint,5,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_60d6484c15673ba5, []int{1}
}
func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (dst *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(dst, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

func (m *EmailResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *EmailResponse) GetDayLimit() int64 {
	if m != nil {
		return m.DayLimit
	}
	return 0
}

func (m *EmailResponse) GetHourLimit() int64 {
	if m != nil {
		return m.HourLimit
	}
	return 0
}

func (m *EmailResponse) GetMinuteLimit() int64 {
	if m != nil {
		return m.MinuteLimit
	}
	return 0
}

func (m *EmailResponse) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type EmailVerifyRequest struct {
	Type                 EmailRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.EmailRequest_Type" json:"type,omitempty"`
	Email                string            `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AuthCode             string            `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailVerifyRequest) Reset()         { *m = EmailVerifyRequest{} }
func (m *EmailVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*EmailVerifyRequest) ProtoMessage()    {}
func (*EmailVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_60d6484c15673ba5, []int{2}
}
func (m *EmailVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerifyRequest.Unmarshal(m, b)
}
func (m *EmailVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerifyRequest.Marshal(b, m, deterministic)
}
func (dst *EmailVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerifyRequest.Merge(dst, src)
}
func (m *EmailVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_EmailVerifyRequest.Size(m)
}
func (m *EmailVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerifyRequest proto.InternalMessageInfo

func (m *EmailVerifyRequest) GetType() EmailRequest_Type {
	if m != nil {
		return m.Type
	}
	return EmailRequest_UNDEFINED
}

func (m *EmailVerifyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailVerifyRequest) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

type EmailCheckRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailCheckRequest) Reset()         { *m = EmailCheckRequest{} }
func (m *EmailCheckRequest) String() string { return proto.CompactTextString(m) }
func (*EmailCheckRequest) ProtoMessage()    {}
func (*EmailCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_60d6484c15673ba5, []int{3}
}
func (m *EmailCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailCheckRequest.Unmarshal(m, b)
}
func (m *EmailCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailCheckRequest.Marshal(b, m, deterministic)
}
func (dst *EmailCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailCheckRequest.Merge(dst, src)
}
func (m *EmailCheckRequest) XXX_Size() int {
	return xxx_messageInfo_EmailCheckRequest.Size(m)
}
func (m *EmailCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailCheckRequest proto.InternalMessageInfo

func (m *EmailCheckRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailRequest)(nil), "protos.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "protos.EmailResponse")
	proto.RegisterType((*EmailVerifyRequest)(nil), "protos.EmailVerifyRequest")
	proto.RegisterType((*EmailCheckRequest)(nil), "protos.EmailCheckRequest")
	proto.RegisterEnum("protos.EmailRequest_Type", EmailRequest_Type_name, EmailRequest_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	VerifyEmail(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*ServerStatus, error)
	CheckEmail(ctx context.Context, in *EmailCheckRequest, opts ...grpc.CallOption) (*ServerStatus, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/protos.Email/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) VerifyEmail(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Email/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) CheckEmail(ctx context.Context, in *EmailCheckRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Email/CheckEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	SendEmail(context.Context, *EmailRequest) (*EmailResponse, error)
	VerifyEmail(context.Context, *EmailVerifyRequest) (*ServerStatus, error)
	CheckEmail(context.Context, *EmailCheckRequest) (*ServerStatus, error)
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Email/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Email/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).VerifyEmail(ctx, req.(*EmailVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_CheckEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).CheckEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Email/CheckEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).CheckEmail(ctx, req.(*EmailCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Email_SendEmail_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _Email_VerifyEmail_Handler,
		},
		{
			MethodName: "CheckEmail",
			Handler:    _Email_CheckEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utlcore/email.proto",
}

func init() { proto.RegisterFile("utlcore/email.proto", fileDescriptor_email_60d6484c15673ba5) }

var fileDescriptor_email_60d6484c15673ba5 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4b, 0x6f, 0xda, 0x4e,
	0x14, 0xc5, 0xe3, 0xf0, 0x08, 0xbe, 0x79, 0xc8, 0x99, 0x90, 0x7f, 0xf8, 0x83, 0x2a, 0xa5, 0x5e,
	0xa5, 0x95, 0x02, 0x55, 0xba, 0xeb, 0xa6, 0x32, 0xf6, 0xa4, 0x58, 0x05, 0x83, 0xc6, 0x26, 0x28,
	0xdd, 0x58, 0x8e, 0x99, 0x1a, 0x2b, 0xc0, 0xb8, 0x7e, 0xa4, 0xe5, 0x6b, 0x75, 0xdf, 0x65, 0xd5,
	0xaf, 0x55, 0x79, 0xc6, 0x50, 0xa8, 0xda, 0x5d, 0x57, 0xd6, 0x3d, 0xe7, 0xe7, 0x33, 0x73, 0xef,
	0xcc, 0xc0, 0x59, 0x96, 0xce, 0x7d, 0x16, 0xd3, 0x0e, 0x5d, 0x78, 0xe1, 0xbc, 0x1d, 0xc5, 0x2c,
	0x65, 0xa8, 0xca, 0x3f, 0x49, 0xb3, 0xbe, 0x36, 0x7d, 0xb6, 0x58, 0xb0, 0xa5, 0x70, 0xd5, 0xef,
	0xfb, 0x70, 0x84, 0x73, 0x9a, 0xd0, 0x4f, 0x19, 0x4d, 0x52, 0x74, 0x0d, 0xe5, 0x74, 0x15, 0xd1,
	0x86, 0x74, 0x29, 0x5d, 0x9d, 0xdc, 0xfc, 0x2f, 0xb0, 0xa4, 0xbd, 0xcd, 0xb4, 0x9d, 0x55, 0x44,
	0x09, 0xc7, 0x50, 0x1d, 0x2a, 0x7c, 0xb1, 0xc6, 0xfe, 0xa5, 0x74, 0x25, 0x13, 0x51, 0xa0, 0x57,
	0x50, 0x9b, 0x7b, 0xcb, 0x20, 0xf3, 0x02, 0xda, 0x28, 0xf1, 0xa0, 0xfa, 0x3a, 0xa8, 0x5f, 0xe8,
	0x3c, 0x63, 0x43, 0xa9, 0xdf, 0x24, 0x28, 0xe7, 0x12, 0x3a, 0x06, 0x79, 0x6c, 0x19, 0xf8, 0xd6,
	0xb4, 0xb0, 0xa1, 0xec, 0xa1, 0x13, 0x00, 0x4d, 0x77, 0xcc, 0x3b, 0xcd, 0x31, 0x87, 0x96, 0x22,
	0xa1, 0x43, 0x38, 0x98, 0xe0, 0xbe, 0x3e, 0x1c, 0x60, 0x65, 0x1f, 0x9d, 0xc3, 0x69, 0xd7, 0xb4,
	0x0c, 0x77, 0xd4, 0x1b, 0x5a, 0xd8, 0xb5, 0xc6, 0x83, 0x2e, 0x26, 0x4a, 0x09, 0x5d, 0xc0, 0x99,
	0xde, 0xd3, 0xac, 0x77, 0x78, 0xd7, 0x28, 0x23, 0x04, 0x27, 0x04, 0xdb, 0xd8, 0x71, 0x47, 0x9a,
	0x6d, 0x4f, 0x86, 0xc4, 0x50, 0x2a, 0xa8, 0x05, 0x17, 0x42, 0xd3, 0xc7, 0x84, 0x60, 0x4b, 0xbf,
	0xff, 0x65, 0x56, 0x51, 0x1d, 0x94, 0x89, 0xe9, 0xf4, 0x0c, 0xa2, 0x4d, 0x5c, 0x03, 0x8f, 0x86,
	0xb6, 0xe9, 0x28, 0x07, 0x79, 0x8c, 0x4e, 0xb0, 0xe6, 0x60, 0x57, 0x1b, 0x99, 0xee, 0x7b, 0x7c,
	0xaf, 0xd4, 0xd4, 0xaf, 0x12, 0x1c, 0x17, 0x33, 0x4a, 0x22, 0xb6, 0x4c, 0x28, 0x7a, 0x09, 0xd5,
	0x24, 0xf5, 0xd2, 0x2c, 0x29, 0x46, 0x89, 0xd6, 0x13, 0xb0, 0xb9, 0xaa, 0xb3, 0x29, 0x25, 0x05,
	0x81, 0x5a, 0x20, 0x4f, 0xbd, 0x95, 0x3b, 0x0f, 0x17, 0x61, 0xca, 0x27, 0x59, 0x22, 0xb5, 0xa9,
	0xb7, 0xea, 0xe7, 0x35, 0x7a, 0x06, 0x30, 0x63, 0x59, 0x5c, 0xb8, 0x25, 0xee, 0xca, 0xb9, 0x22,
	0xec, 0xe7, 0x70, 0xb4, 0x08, 0x97, 0x59, 0x4a, 0x0b, 0xa0, 0xcc, 0x81, 0x43, 0xa1, 0x09, 0xe4,
	0x3f, 0xa8, 0xd2, 0x2f, 0x51, 0x18, 0xd3, 0x46, 0x85, 0x9b, 0x45, 0xa5, 0x3e, 0x01, 0xe2, 0x7b,
	0xbe, 0xa3, 0x71, 0xf8, 0x71, 0xf5, 0x4f, 0x6f, 0x40, 0x0b, 0x64, 0x2f, 0x4b, 0x67, 0xae, 0xcf,
	0xa6, 0xe2, 0x0a, 0xc8, 0xa4, 0x96, 0x0b, 0x79, 0xdb, 0xea, 0x0b, 0x38, 0xe5, 0x69, 0xfa, 0x8c,
	0xfa, 0x8f, 0xeb, 0x65, 0x37, 0x39, 0xd2, 0x56, 0xce, 0xcd, 0x0f, 0x09, 0x2a, 0x9c, 0x45, 0x6f,
	0x40, 0xb6, 0xe9, 0x72, 0x2a, 0x8a, 0xfa, 0x9f, 0x76, 0xd5, 0x3c, 0xff, 0x4d, 0x15, 0x27, 0xa1,
	0xee, 0x21, 0x0d, 0x0e, 0x45, 0x8f, 0xe2, 0xef, 0xe6, 0x0e, 0xb7, 0xd3, 0x7d, 0x73, 0x93, 0x6c,
	0xd3, 0xf8, 0x89, 0xc6, 0xe2, 0xb0, 0xd4, 0x3d, 0xf4, 0x16, 0x80, 0x6f, 0x57, 0x24, 0xec, 0x4e,
	0x65, 0xbb, 0x8f, 0xbf, 0x05, 0x74, 0x31, 0x34, 0x59, 0x1c, 0xb4, 0x1f, 0x18, 0x4b, 0xbd, 0x28,
	0x5a, 0x43, 0xc5, 0xa3, 0xec, 0xc2, 0xe0, 0x56, 0x1b, 0x79, 0xfe, 0xa3, 0x17, 0xd0, 0x0f, 0xad,
	0x20, 0x8e, 0xfc, 0xeb, 0xe4, 0xb3, 0x17, 0x04, 0x34, 0xee, 0x08, 0xb0, 0x53, 0x80, 0x0f, 0xe2,
	0x39, 0xbf, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x4b, 0x2d, 0x8f, 0xec, 0x03, 0x00, 0x00,
}
