// Code generated by protoc-gen-go. DO NOT EDIT.
// source: utlcore/sms.proto

package utlcore // import "grpc-swagger/protos/utlcore"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SMSRequest_Type int32

const (
	SMSRequest_UNDEFINED               SMSRequest_Type = 0
	SMSRequest_REGISTER                SMSRequest_Type = 1
	SMSRequest_LOGIN                   SMSRequest_Type = 2
	SMSRequest_LOGIN_NOTICE            SMSRequest_Type = 3
	SMSRequest_CHANGE_PASSWORD         SMSRequest_Type = 4
	SMSRequest_RESET_PASSWORD          SMSRequest_Type = 5
	SMSRequest_BIND_PHONE_NUMBER       SMSRequest_Type = 6
	SMSRequest_CHANGE_OLD_PHONE        SMSRequest_Type = 7
	SMSRequest_CHANGE_NEW_PHONE        SMSRequest_Type = 8
	SMSRequest_BIND_GA                 SMSRequest_Type = 9
	SMSRequest_RESET_GA                SMSRequest_Type = 10
	SMSRequest_SET_CURRENCY_PASSWORD   SMSRequest_Type = 11
	SMSRequest_RESET_CURRENCY_PASSWORD SMSRequest_Type = 12
	SMSRequest_CURRENCY_NO_PASSWORD    SMSRequest_Type = 13
	SMSRequest_ADD_WITHDRAW_ADDRESS    SMSRequest_Type = 14
	SMSRequest_WITHDRAW_DEPOSIT        SMSRequest_Type = 15
	SMSRequest_WITHDRAW_CONFIRM        SMSRequest_Type = 16
	SMSRequest_WITHDRAW_NOTICE         SMSRequest_Type = 17
	SMSRequest_CREATE_API_KEY          SMSRequest_Type = 18
	SMSRequest_CHECK_API_KEY           SMSRequest_Type = 19
)

var SMSRequest_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "LOGIN",
	3:  "LOGIN_NOTICE",
	4:  "CHANGE_PASSWORD",
	5:  "RESET_PASSWORD",
	6:  "BIND_PHONE_NUMBER",
	7:  "CHANGE_OLD_PHONE",
	8:  "CHANGE_NEW_PHONE",
	9:  "BIND_GA",
	10: "RESET_GA",
	11: "SET_CURRENCY_PASSWORD",
	12: "RESET_CURRENCY_PASSWORD",
	13: "CURRENCY_NO_PASSWORD",
	14: "ADD_WITHDRAW_ADDRESS",
	15: "WITHDRAW_DEPOSIT",
	16: "WITHDRAW_CONFIRM",
	17: "WITHDRAW_NOTICE",
	18: "CREATE_API_KEY",
	19: "CHECK_API_KEY",
}
var SMSRequest_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"REGISTER":                1,
	"LOGIN":                   2,
	"LOGIN_NOTICE":            3,
	"CHANGE_PASSWORD":         4,
	"RESET_PASSWORD":          5,
	"BIND_PHONE_NUMBER":       6,
	"CHANGE_OLD_PHONE":        7,
	"CHANGE_NEW_PHONE":        8,
	"BIND_GA":                 9,
	"RESET_GA":                10,
	"SET_CURRENCY_PASSWORD":   11,
	"RESET_CURRENCY_PASSWORD": 12,
	"CURRENCY_NO_PASSWORD":    13,
	"ADD_WITHDRAW_ADDRESS":    14,
	"WITHDRAW_DEPOSIT":        15,
	"WITHDRAW_CONFIRM":        16,
	"WITHDRAW_NOTICE":         17,
	"CREATE_API_KEY":          18,
	"CHECK_API_KEY":           19,
}

func (x SMSRequest_Type) String() string {
	return proto.EnumName(SMSRequest_Type_name, int32(x))
}
func (SMSRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sms_7d486ce955c135ab, []int{0, 0}
}

type SMSRequest struct {
	Aaa                  SMSRequest_Type `protobuf:"varint,1,opt,name=aaa,proto3,enum=protos.SMSRequest_Type" json:"aaa,omitempty"`
	PhoneNumber          string          `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Content              string          `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SMSRequest) Reset()         { *m = SMSRequest{} }
func (m *SMSRequest) String() string { return proto.CompactTextString(m) }
func (*SMSRequest) ProtoMessage()    {}
func (*SMSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sms_7d486ce955c135ab, []int{0}
}
func (m *SMSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSRequest.Unmarshal(m, b)
}
func (m *SMSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSRequest.Marshal(b, m, deterministic)
}
func (dst *SMSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSRequest.Merge(dst, src)
}
func (m *SMSRequest) XXX_Size() int {
	return xxx_messageInfo_SMSRequest.Size(m)
}
func (m *SMSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SMSRequest proto.InternalMessageInfo

func (m *SMSRequest) GetAaa() SMSRequest_Type {
	if m != nil {
		return m.Aaa
	}
	return SMSRequest_UNDEFINED
}

func (m *SMSRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SMSRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SMSResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	DayLimit             int64      `protobuf:"varint,2,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	HourLimit            int64      `protobuf:"varint,3,opt,name=hour_limit,json=hourLimit,proto3" json:"hour_limit,omitempty"`
	MinuteLimit          int64      `protobuf:"varint,4,opt,name=minute_limit,json=minuteLimit,proto3" json:"minute_limit,omitempty"`
	Expire               int64      `protobuf:"varint,5,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SMSResponse) Reset()         { *m = SMSResponse{} }
func (m *SMSResponse) String() string { return proto.CompactTextString(m) }
func (*SMSResponse) ProtoMessage()    {}
func (*SMSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sms_7d486ce955c135ab, []int{1}
}
func (m *SMSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSResponse.Unmarshal(m, b)
}
func (m *SMSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSResponse.Marshal(b, m, deterministic)
}
func (dst *SMSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSResponse.Merge(dst, src)
}
func (m *SMSResponse) XXX_Size() int {
	return xxx_messageInfo_SMSResponse.Size(m)
}
func (m *SMSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SMSResponse proto.InternalMessageInfo

func (m *SMSResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *SMSResponse) GetDayLimit() int64 {
	if m != nil {
		return m.DayLimit
	}
	return 0
}

func (m *SMSResponse) GetHourLimit() int64 {
	if m != nil {
		return m.HourLimit
	}
	return 0
}

func (m *SMSResponse) GetMinuteLimit() int64 {
	if m != nil {
		return m.MinuteLimit
	}
	return 0
}

func (m *SMSResponse) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type SMSVerifyRequest struct {
	Type                 SMSRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.SMSRequest_Type" json:"type,omitempty"`
	PhoneNumber          string          `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	AuthCode             string          `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SMSVerifyRequest) Reset()         { *m = SMSVerifyRequest{} }
func (m *SMSVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*SMSVerifyRequest) ProtoMessage()    {}
func (*SMSVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sms_7d486ce955c135ab, []int{2}
}
func (m *SMSVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerifyRequest.Unmarshal(m, b)
}
func (m *SMSVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerifyRequest.Marshal(b, m, deterministic)
}
func (dst *SMSVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerifyRequest.Merge(dst, src)
}
func (m *SMSVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_SMSVerifyRequest.Size(m)
}
func (m *SMSVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerifyRequest proto.InternalMessageInfo

func (m *SMSVerifyRequest) GetType() SMSRequest_Type {
	if m != nil {
		return m.Type
	}
	return SMSRequest_UNDEFINED
}

func (m *SMSVerifyRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SMSVerifyRequest) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

type CheckPhoneRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPhoneRequest) Reset()         { *m = CheckPhoneRequest{} }
func (m *CheckPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPhoneRequest) ProtoMessage()    {}
func (*CheckPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sms_7d486ce955c135ab, []int{3}
}
func (m *CheckPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPhoneRequest.Unmarshal(m, b)
}
func (m *CheckPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPhoneRequest.Marshal(b, m, deterministic)
}
func (dst *CheckPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPhoneRequest.Merge(dst, src)
}
func (m *CheckPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPhoneRequest.Size(m)
}
func (m *CheckPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPhoneRequest proto.InternalMessageInfo

func (m *CheckPhoneRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*SMSRequest)(nil), "protos.SMSRequest")
	proto.RegisterType((*SMSResponse)(nil), "protos.SMSResponse")
	proto.RegisterType((*SMSVerifyRequest)(nil), "protos.SMSVerifyRequest")
	proto.RegisterType((*CheckPhoneRequest)(nil), "protos.CheckPhoneRequest")
	proto.RegisterEnum("protos.SMSRequest_Type", SMSRequest_Type_name, SMSRequest_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsClient interface {
	SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*SMSResponse, error)
	VerifySMS(ctx context.Context, in *SMSVerifyRequest, opts ...grpc.CallOption) (*ServerStatus, error)
	CheckPhone(ctx context.Context, in *CheckPhoneRequest, opts ...grpc.CallOption) (*ServerStatus, error)
}

type smsClient struct {
	cc *grpc.ClientConn
}

func NewSmsClient(cc *grpc.ClientConn) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*SMSResponse, error) {
	out := new(SMSResponse)
	err := c.cc.Invoke(ctx, "/protos.Sms/SendSMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) VerifySMS(ctx context.Context, in *SMSVerifyRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Sms/VerifySMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CheckPhone(ctx context.Context, in *CheckPhoneRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Sms/CheckPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
type SmsServer interface {
	SendSMS(context.Context, *SMSRequest) (*SMSResponse, error)
	VerifySMS(context.Context, *SMSVerifyRequest) (*ServerStatus, error)
	CheckPhone(context.Context, *CheckPhoneRequest) (*ServerStatus, error)
}

func RegisterSmsServer(s *grpc.Server, srv SmsServer) {
	s.RegisterService(&_Sms_serviceDesc, srv)
}

func _Sms_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sms/SendSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).SendSMS(ctx, req.(*SMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_VerifySMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).VerifySMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sms/VerifySMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).VerifySMS(ctx, req.(*SMSVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CheckPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CheckPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sms/CheckPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CheckPhone(ctx, req.(*CheckPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSMS",
			Handler:    _Sms_SendSMS_Handler,
		},
		{
			MethodName: "VerifySMS",
			Handler:    _Sms_VerifySMS_Handler,
		},
		{
			MethodName: "CheckPhone",
			Handler:    _Sms_CheckPhone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utlcore/sms.proto",
}

func init() { proto.RegisterFile("utlcore/sms.proto", fileDescriptor_sms_7d486ce955c135ab) }

var fileDescriptor_sms_7d486ce955c135ab = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xc7, 0x43, 0x20, 0x80, 0x0f, 0x24, 0x19, 0x26, 0xa4, 0x21, 0xd0, 0x4a, 0x09, 0x57, 0x69,
	0xab, 0xe2, 0x36, 0x95, 0x72, 0x57, 0x55, 0xc6, 0x9e, 0x80, 0x95, 0x60, 0xa3, 0x31, 0x29, 0x4a,
	0x6f, 0x2c, 0xc7, 0x4c, 0xc1, 0x4d, 0xf0, 0xb8, 0xfe, 0x48, 0x8b, 0xa2, 0xa8, 0x52, 0x1f, 0xa1,
	0xbd, 0xec, 0x4b, 0xf4, 0x5d, 0xfa, 0x0a, 0xfb, 0x02, 0xfb, 0x06, 0x2b, 0x7f, 0x00, 0xc9, 0xa2,
	0xd5, 0xee, 0x15, 0x9e, 0xdf, 0xff, 0x3f, 0xe7, 0x9c, 0x39, 0x73, 0x18, 0xa8, 0x45, 0xe1, 0x83,
	0xcd, 0x7d, 0x26, 0x06, 0xf3, 0xa0, 0xe3, 0xf9, 0x3c, 0xe4, 0xb8, 0x98, 0xfc, 0x04, 0xcd, 0xfa,
	0x52, 0xb2, 0xf9, 0x7c, 0xce, 0xdd, 0x54, 0x6d, 0x7e, 0x3e, 0xe5, 0x7c, 0xfa, 0xc0, 0x44, 0xcb,
	0x73, 0x44, 0xcb, 0x75, 0x79, 0x68, 0x85, 0x0e, 0x77, 0xb3, 0xbd, 0xed, 0xbf, 0x0b, 0x00, 0xc6,
	0xc0, 0xa0, 0xec, 0xb7, 0x88, 0x05, 0x21, 0xfe, 0x12, 0xf2, 0x96, 0x65, 0x35, 0x72, 0x27, 0xb9,
	0xb3, 0xbd, 0xf3, 0xa3, 0xd4, 0x13, 0x74, 0xd6, 0x86, 0xce, 0x68, 0xe1, 0x31, 0x1a, 0x7b, 0xf0,
	0x29, 0x54, 0xbd, 0x19, 0x77, 0x99, 0xe9, 0x46, 0xf3, 0x3b, 0xe6, 0x37, 0xb6, 0x4f, 0x72, 0x67,
	0x02, 0xad, 0x24, 0x4c, 0x4b, 0x10, 0x6e, 0x40, 0xc9, 0xe6, 0x6e, 0xc8, 0xdc, 0xb0, 0x91, 0x4f,
	0xd4, 0xe5, 0xb2, 0xfd, 0x6f, 0x1e, 0x0a, 0x71, 0x28, 0xbc, 0x0b, 0xc2, 0x8d, 0xa6, 0x90, 0x4b,
	0x55, 0x23, 0x0a, 0xda, 0xc2, 0x55, 0x28, 0x53, 0xd2, 0x53, 0x8d, 0x11, 0xa1, 0x28, 0x87, 0x05,
	0xd8, 0xb9, 0xd6, 0x7b, 0xaa, 0x86, 0xb6, 0x31, 0x82, 0x6a, 0xf2, 0x69, 0x6a, 0xfa, 0x48, 0x95,
	0x09, 0xca, 0xe3, 0x03, 0xd8, 0x97, 0xfb, 0x92, 0xd6, 0x23, 0xe6, 0x50, 0x32, 0x8c, 0xb1, 0x4e,
	0x15, 0x54, 0xc0, 0x18, 0xf6, 0x28, 0x31, 0xc8, 0x68, 0xcd, 0x76, 0xf0, 0x21, 0xd4, 0xba, 0xaa,
	0xa6, 0x98, 0xc3, 0xbe, 0xae, 0x11, 0x53, 0xbb, 0x19, 0x74, 0x09, 0x45, 0x45, 0x5c, 0x07, 0x94,
	0xed, 0xd7, 0xaf, 0x33, 0x11, 0x95, 0x5e, 0x50, 0x8d, 0x8c, 0x33, 0x5a, 0xc6, 0x15, 0x28, 0x25,
	0x21, 0x7a, 0x12, 0x12, 0xd2, 0x1a, 0xe3, 0x1c, 0x3d, 0x09, 0x01, 0x3e, 0x86, 0xc3, 0xf8, 0x5b,
	0xbe, 0xa1, 0x94, 0x68, 0xf2, 0xed, 0x3a, 0x71, 0x05, 0xb7, 0xe0, 0x28, 0x35, 0x6e, 0x8a, 0x55,
	0xdc, 0x80, 0xfa, 0x0a, 0x6b, 0xfa, 0x5a, 0xd9, 0x8d, 0x15, 0x49, 0x51, 0xcc, 0xb1, 0x3a, 0xea,
	0x2b, 0x54, 0x1a, 0x9b, 0x92, 0xa2, 0x50, 0x62, 0x18, 0x68, 0x2f, 0x2e, 0x6e, 0x45, 0x15, 0x32,
	0xd4, 0x0d, 0x75, 0x84, 0xf6, 0x5f, 0x51, 0x59, 0xd7, 0x2e, 0x55, 0x3a, 0x40, 0x28, 0x6e, 0xcf,
	0x8a, 0x66, 0x3d, 0xab, 0xc5, 0xed, 0x91, 0x29, 0x91, 0x46, 0xc4, 0x94, 0x86, 0xaa, 0x79, 0x45,
	0x6e, 0x11, 0xc6, 0x35, 0xd8, 0x95, 0xfb, 0x44, 0xbe, 0x5a, 0xa1, 0x83, 0xf6, 0x7f, 0x39, 0xa8,
	0x24, 0x77, 0x1e, 0x78, 0xdc, 0x0d, 0x18, 0xfe, 0x0a, 0x8a, 0x41, 0x68, 0x85, 0x51, 0x90, 0x0d,
	0x06, 0x5e, 0x0d, 0x46, 0x42, 0x65, 0x3e, 0x61, 0x34, 0x73, 0xe0, 0x16, 0x08, 0x13, 0x6b, 0x61,
	0x3e, 0x38, 0x73, 0x27, 0x4c, 0x66, 0x22, 0x4f, 0xcb, 0x13, 0x6b, 0x71, 0x1d, 0xaf, 0xf1, 0x17,
	0x00, 0x33, 0x1e, 0xf9, 0x99, 0x9a, 0x4f, 0x54, 0x21, 0x26, 0xa9, 0x7c, 0x0a, 0xd5, 0xb9, 0xe3,
	0x46, 0x21, 0xcb, 0x0c, 0x85, 0xc4, 0x50, 0x49, 0x59, 0x6a, 0xf9, 0x0c, 0x8a, 0xec, 0x0f, 0xcf,
	0xf1, 0x59, 0x63, 0x27, 0x11, 0xb3, 0x55, 0xfb, 0x4f, 0x40, 0xc6, 0xc0, 0xf8, 0x89, 0xf9, 0xce,
	0x2f, 0x8b, 0xe5, 0x30, 0x7f, 0x0d, 0x85, 0x70, 0xe1, 0xb1, 0x8f, 0x4d, 0x73, 0x62, 0xfa, 0x94,
	0x71, 0x6e, 0x81, 0x60, 0x45, 0xe1, 0xcc, 0xb4, 0xf9, 0x84, 0x65, 0x03, 0x5d, 0x8e, 0x41, 0x7c,
	0xfe, 0xf6, 0x05, 0xd4, 0xe4, 0x19, 0xb3, 0xef, 0x87, 0xf1, 0x86, 0x65, 0x05, 0xef, 0x07, 0xcd,
	0x6d, 0x04, 0x3d, 0x7f, 0x9b, 0x83, 0xbc, 0x31, 0x0f, 0xf0, 0xaf, 0x50, 0x32, 0x98, 0x3b, 0x31,
	0x06, 0x06, 0xc6, 0x9b, 0x95, 0x36, 0x0f, 0x5e, 0xb1, 0xf4, 0x5e, 0xda, 0x17, 0x7f, 0xfd, 0xff,
	0xe6, 0x9f, 0xed, 0x6f, 0x71, 0x47, 0x7c, 0xfc, 0x4e, 0x0c, 0x98, 0x1d, 0xf9, 0x4e, 0xb8, 0x88,
	0x1f, 0x06, 0x31, 0x60, 0xee, 0x44, 0x7c, 0x7a, 0x99, 0xfb, 0x59, 0x7c, 0xca, 0xfe, 0x7c, 0xcf,
	0xf8, 0x07, 0x10, 0xd2, 0x4e, 0xc5, 0xd9, 0x1a, 0x2f, 0x22, 0xbf, 0xea, 0x5f, 0xb3, 0xbe, 0x52,
	0x98, 0xff, 0xc8, 0xfc, 0xf4, 0xb2, 0xdb, 0x5b, 0xf8, 0x47, 0x80, 0xf5, 0x51, 0xf1, 0xf1, 0xd2,
	0xb5, 0x71, 0xfc, 0x0f, 0x05, 0xe8, 0x12, 0x68, 0x72, 0x7f, 0xda, 0xb9, 0xe3, 0x3c, 0xb4, 0x3c,
	0x6f, 0x69, 0xca, 0x5e, 0xaf, 0x2e, 0x0c, 0x2e, 0xa5, 0xa1, 0x65, 0xdf, 0x5b, 0x53, 0xf6, 0x73,
	0x6b, 0xea, 0x7b, 0xf6, 0x37, 0xc1, 0xef, 0xd6, 0x74, 0xca, 0x7c, 0x31, 0x35, 0x8a, 0x99, 0xf1,
	0x2e, 0x7d, 0xf7, 0xbe, 0x7f, 0x17, 0x00, 0x00, 0xff, 0xff, 0x17, 0xfa, 0x80, 0xb0, 0x13, 0x05,
	0x00, 0x00,
}
